### ISSUE TITLE
Hi, I don't get how you manage to generate a cfg file with only a .pt file as input. It seems to me that there is some file missing to the conversion from pytorch .pt to darknet (.weight + .cfg) 

### ISSUE THREAD

**Issue by Foglia-m** [sabari50312/WeaponDetectionYoloV5#1]

**Comment by sabari50312** [comment]
.pt file was all it took. Detailed steps are given here https://github.com/marcoslucianops/DeepStream-Yolo#basic-usage.
I just followed them

**Comment by sabari50312** [comment]
.

> .pt file was all it took. Detailed steps are given here https://github.com/marcoslucianops/DeepStream-Yolo#basic-usage. I just followed them
